### ISSUE TITLE
Use an alternative to Lenna for image samples

### ISSUE THREAD

**Issue by cocoademon** [google/knusperli#4]
The Lenna/Lena image is from a Playboy centrefold. The image compression community has been moving away from its use since the 1990's.

There are plenty of alternative images that you can use to demonstrate deblocking, including some that have been around nearly as long as Lenna, such as Mandrill or Peppers, available here: http://sipi.usc.edu/database/database.php?volume=misc&image=13#top

Note also that SIPI has removed access to Lenna as well as other images of dubious origin.

**Comment by tagcup** [comment]
Aren't people allowed to enjoy Playboy or whatever for their own stuff anymore, or is it the new norm for Social Justice Warriors to attack people's freedom of expression when it doesn't conform to their world view?

**Comment by jlfwong** [comment]
@tagcup They are absolutely allowed to enjoy it on their own stuff, but that doesn't make it a sensible choice for a demonstration of image compression. If the image were hardcore pornography, it would seem obviously out of place. The fact is this is cropped pornography. People are certainly politically free to have their test image be a giant sign that says "FUCK YOU", but, you know, it's probably not the most welcoming choice.

**Comment by Yetangitu** [comment]
As far as I know Lena Söderberg voluntarily had her picture taken by Playboy magazine, she even got paid for it. Nobody asked the mandrill if he wanted to have his picture taken and he never got paid a single banana for the rights. Those peppers, let's not mention them as the story is too gruesome to tell. Suffice to say that shortly after the picture was take they were mercilessly cut to bits and devoured by the photographer and his accomplices.

So here we have one photo which arose in freedom, of free will, portraying a consenting adult. Another taken in captivity, taken without prior consent. A third which might as well be subtitled 'Morituri te salutant'. Now I ask you, which of these photo's should be used and which should be shunned? The choice is yours as long as you are willing to stand by it.

**Comment by Anamon** [comment]
The alternatives suggested by the original ticket are of similarly dubious origins. The issue with the Lena picture is its copyrighted status, with its uses in the community often stretching the limits of fair use. The SIPI images are for the most part, just like Lena, copyrighted and used without permission.

**Comment by Yetangitu** [comment]
Lena has gone - or is that should have gone - the way of Aspirin, by now that image has been (ab)used so much that I don't see the copyright holder stand a chance if they were to try a case.

**Comment by jyrkialakuijala** [comment]
Thank you everyone for sharing your views on this topic. We don't want to signal anything with our selection of test images. If someone feels strongly about this and wants to make a pull request to change to another image that shows knusperli's behavior, I'd approve it. Naturally the new image should show the decoding differences roughly equally well and be from a source that makes the copyright issues obviously solved.

I removed quite a few comments because the ethical discussion on this topic is better to happen on some other more appropriate forum.

No one needs to get sad because of this: If you feel strongly pro-Lena, just clone the repo and keep Lena. (And if you feel opposite, help us and send a PR to replace Lena.)

**Comment by tagcup** [comment]
@jlfwong It's totally sensible to me, as well as many others for decades. The fact that it was originally cropped from a piece of consensual erotica doesn't bother me at all; I don't think her face (which is what is depicted in that picture) is tainted in any way as I don't have any religious prejudice against erotica, or even porn. And no, you can't force your zeal into other's throats because last time I checked we're still living in a free country.
